spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: asdf
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

# names: ${job.name:NONE}  Program arguments: --job.name=???
# Active profiles: mysql
