spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver


# names: ${job.name:NONE}  Program arguments: --job.name=???

